### ISSUE TITLE
hops test fails on missing 3593.tar.gz

### ISSUE THREAD

**Issue by jwagnerhki** [difx/difx#23]
Under git rev 412095b and earlier,

```
make[2]: Entering directory `/cluster/difx/DiFX-git/jwagner/git/applications/hops/chops/source/python_src/tests'
make[2]: *** No rule to make target `3593.tar.gz', needed by `all-am'.  Stop.
make[2]: Leaving directory `/cluster/difx/DiFX-git/jwagner/git/applications/hops/chops/source/python_src/tests'
make[1]: *** [all-recursive] Error 1
```

The large binary .tar.gz file is in the old SVN repository, but for good reason not in git.

Update the 'make' process so that it downloads a local copy before it tries to run the tests?

**Comment by jwagnerhki** [comment]
Even with "-k" the build fails:

`[difx@fxmanager git-build]$ export MAKEFLAGS="-j1 -k"
[difx@fxmanager git-build]$ $DIFXROOT/git/install-difx --reconf --doonly=hops
...
make[2]: Leaving directory `/cluster/difx/DiFX-git/jwagner/git-build/applications/hops/vex2xml'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/cluster/difx/DiFX-git/jwagner/git-build/applications/hops'
make: *** [all] Error 2
Traceback (most recent call last):
  File "/cluster/difx/DiFX-git/jwagner//git/install-difx", line 946, in <module>
    difxroot, apptarget[5])
  File "/cluster/difx/DiFX-git/jwagner//git/install-difx", line 653, in auto_compile
    run(MAKEcommand + target)
  File "/cluster/difx/DiFX-git/jwagner//git/install-difx", line 601, in run
    raise RuntimeError("Error running " + cmd + " in " + os.getcwd())
RuntimeError: Error running make all in /cluster/difx/DiFX-git/jwagner/git-build/applications/hops
`

**Comment by gbcrew** [comment]
What can I say but that we only just migrated the code and I haven't had time to do anything with it.  So give us a chance, ok?

**Comment by shaoguangleo** [comment]
Hi @jwagnerhki , please see #24 for more details.
We will borrow the big files in another repo using sub-module as discussed last time.

**Comment by shaoguangleo** [comment]
Hi @jwagnerhki , please see #24 for more details.
We will borrow the big files in another repo using submodle as discussed last time.

**Comment by jwagnerhki** [comment]
Thanks @shaoguangleo and Geoff - the full DiFX tree builds fine now, I'll close this.
